### ISSUE TITLE
🐞 ExceptionReporter does not work under windows server 2019 🐞

### ISSUE THREAD

**Issue by alex-held** [wonderbird/RemoteControlledProcess#9]
# ExceptionReporter does not work under windows server 2019

## Problem
Under macOS Catalina 10.05 and Ubuntu 20 LTS, the tests are working as expected.
[Look at this Pull Request](https://github.com/alex-held/RemoteControlledProcess/pull/1)

#### The worst part is, that the exception seems to cause the test host to not shut down.

That means the `dotnet test` process will run indefinitely until manually killed. 

This is pretty bad if you want to execute the test in pipelines.

#
## Question

Should I ditch the support for windows inside the test pipelines, or what do you suggest?

## Additional Information

For more information please look into the [full logs](https://github.com/alex-held/RemoteControlledProcess/pull/1/checks?check_run_id=1850100654#step:9:168)

> Starting:    RemoteControlledProcess.Unit.Tests
[xUnit.net 00:00:00.81]     RemoteControlledProcess.Unit.Tests.ExceptionReporterExtensionTests.Write_CalledInCatchBlock_WrittenMessagesMatch(invocationIndex: 0, expectedMessageRegex: "Unhandled exception in .*RemoteControlledProcess.U"...) [FAIL]
[xUnit.net 00:00:00.81]       Assert.Matches() Failure:
[xUnit.net 00:00:00.83]     RemoteControlledProcess.Unit.Tests.ExceptionReporterExtensionTests.Log_CalledInCatchBlock_LogsCriticalMessageWithExpectedRegex [FAIL]
Test Run Failed.
[xUnit.net 00:00:00.81]       Regex: Unhandled exception in .*RemoteControlledProcess.Unit.Tests/ExceptionReporterExtensionTests.cs:[0-9]+
[xUnit.net 00:00:00.81]       Value: Unhandled exception in D:\a\RemoteControlledProcess\RemoteControlledProcess\RemoteControlledProcess.Unit.Tests\ExceptionReporterExtensionTests.cs:22
[xUnit.net 00:00:00.81]       Stack Trace:
[xUnit.net 00:00:00.81]         D:\a\RemoteControlledProcess\RemoteControlledProcess\RemoteControlledProcess.Unit.Tests\ExceptionReporterExtensionTests.cs(32,0): at RemoteControlledProcess.Unit.Tests.ExceptionReporterExtensionTests.Write_CalledInCatchBlock_WrittenMessagesMatch(Int32 invocationIndex, String expectedMessageRegex)
[xUnit.net 00:00:00.83]       Assert.Matches() Failure:
[xUnit.net 00:00:00.83]       Regex: Unhandled exception in .*RemoteControlledProcess.Unit.Tests/ExceptionReporterExtensionTests.cs:[0-9]+
[xUnit.net 00:00:00.83]       Value: Unhandled exception in D:\a\RemoteControlledProcess\RemoteControlledProcess\RemoteControlledProcess.Unit.Tests\ExceptionReporterExtensionTests.cs:43
[xUnit.net 00:00:00.83]       Stack Trace:
[xUnit.net 00:00:00.83]         D:\a\RemoteControlledProcess\RemoteControlledProcess\RemoteControlledProcess.Unit.Tests\ExceptionReporterExtensionTests.cs(56,0): at RemoteControlledProcess.Unit.Tests.ExceptionReporterExtensionTests.Log_CalledInCatchBlock_LogsCriticalMessageWithExpectedRegex()

A bug inside unit when running code under windows server 2019

**Comment by alex-held** [comment]
@wonderbird 

I tried to fix the issue described above here in this [pull request](https://github.com/alex-held/RemoteControlledProcess/pull/2).

The test process still does not shut down...
I can merge it if you want it though..

**Comment by wonderbird** [comment]
Hi @alex-held,

Thanks for trying to run the build on macos and windows. Thanks for showing the issue.

Please do not merge a branch with a failing pipeline to main.

Instead I will try to get more information about the issue using [tmate](https://github.com/marketplace/actions/debugging-with-tmate) next.

Cheers
Stefan

**Comment by wonderbird** [comment]
I have re-created the windows build and currently I am debugging it using tmate.

See https://github.com/wonderbird/RemoteControlledProcess/pull/10

**Comment by wonderbird** [comment]
I love Windows backslashes in paths - how about you?

```
# dotnet test RemoteControlledProcess.Unit.Tests/RemoteControlledProcess.Unit.Tests.csproj
  Determining projects to restore...
  All projects are up-to-date for restore.
  RemoteControlledProcess -> D:\a\RemoteControlledProcess\RemoteControlledProcess\RemoteControlledProcess\bin\Debug\net5.0\RemoteControlledProcess.dll
  RemoteControlledProcess.Unit.Tests -> D:\a\RemoteControlledProcess\RemoteControlledProcess\RemoteControlledProcess.Unit.Tests\bin\Debug\net5.0\RemoteControlledProcess.Unit.Tests.dll
Test run for D:\a\RemoteControlledProcess\RemoteControlledProcess\RemoteControlledProcess.Unit.Tests\bin\Debug\net5.0\RemoteControlledProcess.Unit.Tests.dll (.NETCoreApp,Version=v5.0)
Microsoft (R) Test Execution Command Line Tool Version 16.8.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
[xUnit.net 00:00:00.82]     RemoteControlledProcess.Unit.Tests.ExceptionReporterExtensionTests.Write_CalledInCatchBlock_WrittenMessagesMatch(invocationIndex: 0, expectedMessageRegex: "Unhandled exception in .*RemoteControlledProcess.U"...) [FAIL]
[xUnit.net 00:00:00.84]     RemoteControlledProcess.Unit.Tests.ExceptionReporterExtensionTests.Log_CalledInCatchBlock_LogsCriticalMessageWithExpectedRegex [FAIL]
  Failed RemoteControlledProcess.Unit.Tests.ExceptionReporterExtensionTests.Write_CalledInCatchBlock_WrittenMessagesMatch(invocationIndex: 0, expectedMessageRegex: "Unhandled exception in .*RemoteControlledProcess.U"...) [4 ms]
  Error Message:
   Assert.Matches() Failure:
Regex: Unhandled exception in .*RemoteControlledProcess.Unit.Tests/ExceptionReporterExtensionTests.cs:[0-9]+
Value: Unhandled exception in D:\a\RemoteControlledProcess\RemoteControlledProcess\RemoteControlledProcess.Unit.Tests\ExceptionReporterExtensionTests.cs:27
  Stack Trace:
     at RemoteControlledProcess.Unit.Tests.ExceptionReporterExtensionTests.Write_CalledInCatchBlock_WrittenMessagesMatch(Int32 invocationIndex, String expectedMessageRegex) in D:\a\RemoteControlledProcess\RemoteControlledProcess\RemoteControlledProcess.Unit.Tests\ExceptionReporterExtensionTests.cs:line 43
  Standard Output Messages:
 ===== Expected Message Regex:
 "Unhandled exception in .*RemoteControlledProcess.Unit.Tests/ExceptionReporterExtensionTests.cs:[0-9]+"
 ===== Actual Message:
 "Unhandled exception in D:\a\RemoteControlledProcess\RemoteControlledProcess\RemoteControlledProcess.Unit.Tests\ExceptionReporterExtensionTests.cs:27"


  Failed RemoteControlledProcess.Unit.Tests.ExceptionReporterExtensionTests.Log_CalledInCatchBlock_LogsCriticalMessageWithExpectedRegex [27 ms]
  Error Message:
   Assert.Matches() Failure:
Regex: Unhandled exception in .*RemoteControlledProcess.Unit.Tests/ExceptionReporterExtensionTests.cs:[0-9]+
Value: Unhandled exception in D:\a\RemoteControlledProcess\RemoteControlledProcess\RemoteControlledProcess.Unit.Tests\ExceptionReporterExtensionTests.cs:54
  Stack Trace:
     at RemoteControlledProcess.Unit.Tests.ExceptionReporterExtensionTests.Log_CalledInCatchBlock_LogsCriticalMessageWithExpectedRegex() in D:\a\RemoteControlledProcess\RemoteControlledProcess\RemoteControlledProcess.Unit.Tests\ExceptionReporterExtensionTests.cs:line 79
  Standard Output Messages:
 ===== Expected Message Regex:
 "Unhandled exception in .*RemoteControlledProcess.Unit.Tests/ExceptionReporterExtensionTests.cs:[0-9]+"
 ===== Actual Message:
 "Unhandled exception in D:\a\RemoteControlledProcess\RemoteControlledProcess\RemoteControlledProcess.Unit.Tests\ExceptionReporterExtensionTests.cs:54"
 ===== Expected LogLevel:
 "Critical"
 ===== Actual LogLevel:
 "Critical"
```
